Read custom INPI code in xml files to create a metadata.csv file
phe-sto/enthic pull request #4
Opened 2020-11-05 08:50 UTC by leonarf

Je crée cette pull request pour commencer la discussion sur l'import des metadata disponible dans les fichiers xml de bilan comptable de l'INPI : code_motif, code_confidentialite, info_traitement.

1. _code_confidentialite_ nous servira à savoir si une entreprise a déposé ses comptes en confidentiel, ou si elle n'a pas déposé ses comptes.
2. _code_motif_ nous servira a savoir si les erreurs constatées dans le compte de résultat sont imputables plutôt à l'entreprise, ou plutôt à la chaîne d'action qui produit le fichier XML.
3. _info_traitement_ peut permettre de mieux gérer les bilan comptable multiple pour un même couple année/entreprise. Je ne pense pas que sommer les valeurs soit la bonne manière de faire. Il vaudrait mieux garder le dernier fourni. _info_traitement_ peut aussi servir à détecter la source d'incohérence, entre l'administration et l'entreprise.

Pour l'instant le code de la pull request se contente de lire ces 3 champs pour les mettre dans un fichier csv dédié.

2020-11-19 21:38 UTC, phe-sto requested changes
Could you please merge line 125 with 123 and 124.
As far as I understand CODE_MOTIF, CODE_CONFIDENTIALITE, INFO_TRAITEMENT are just the corresponding label of the codes extracted from the XML. They are unused here, is it for future use? Their place is probably in the ontology.py, no?

2020-11-23 13:52 UTC, leonarf commented
> Could you please merge line 125 with 123 and 124.
> As far as I understand CODE_MOTIF, CODE_CONFIDENTIALITE, INFO_TRAITEMENT are just the corresponding label of the codes extracted from the XML. They are unused here, is it for future use? Their place is probably in the ontology.py, no?

Merge done.
I moved CODE_MOTIF, CODE_CONFIDENTIALITE, and INFO_TRAITEMENT into ontology.py, and I think they will be useful to serve these new data through the API, but not yet.
This PullRequest is a first step, to read these new data from xml files and create a csv file with it.
Step 2 would be to use this csv file to add these data into the database
Step 3 would be to add to the API functionalities to get these data.
Step 4 would be to use these data to handle smartly companies that have multiple declaration for a same year (because I think adding these multiple declaration is not the correct way to do this, we should probably take the last one).
I'm open to discuss every step :-)

2020-11-23 14:07 UTC, phe-sto requested changes
Hi, it fine to me, but the pylint decreased above the minimum (initial one at the configuration of CI) i.e. the score should go up.
Please use pylint locally to improve coding style in the modules you have changed. Minimum is 7.8 if I remember correctly.

2020-11-23 16:05 UTC, leonarf commented
> Hi, it fine to me, but the pylint decreased above the minimum (initial one at the configuration of CI) i.e. the score should go up.
> Please use pylint locally to improve coding style in the modules you have changed. Minimum is 7.8 if I remember correctly.

I changed my modification so the code respect more the pylint recommandations. I hope it respect also your vision :-)

2020-11-24 21:09 UTC, phe-sto commented on python/enthic/extract_bundle.py
> +RE_DENOMINATION = compile(r'\s+|[\t\n]')  # NOT AN OBVIOUS PERFORMANCE GAIN...
Salut tu es sûr de la regex? J'ai l'impression que tu vas remplace \t\n et non pas \n ou \t . Tu voudrais plutôt quelque chose comme \s+|\t|\n ?

2020-11-24 21:27 UTC, leonarf commented on python/enthic/extract_bundle.py
> +RE_DENOMINATION = compile(r'\s+|[\t\n]')  # NOT AN OBVIOUS PERFORMANCE GAIN...
J'ai pas testé mais j'en suis presque sûr oui, vu que le \t et \n sont entre crochet [].

2020-11-24 21:35 UTC, phe-sto approved these changes

2020-11-24 21:35 UTC, phe-sto commented on python/enthic/extract_bundle.py
> +RE_DENOMINATION = compile(r'\s+|[\t\n]')  # NOT AN OBVIOUS PERFORMANCE GAIN...
Indeed!

2020-11-24 21:36 UTC, merged